<a href="https://colab.research.google.com/github/Anna72/ML_1_term/blob/main/exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.datasets import mnist
(X_train, y_train), (X_pred, y_pred) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
X_train = X_train[0:3000]
y_train = y_train[0:3000]

dim = 784 # 28*28 
X_train = X_train.reshape(len(X_train), dim)
#y_train = y_train.reshape(len(X_train), dim)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.3, random_state=23)

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
tree = RandomForestClassifier(criterion='gini', min_samples_leaf=10, max_depth=20, n_estimators=10, random_state=23)

clf = OneVsRestClassifier(tree).fit(X_train, y_train)

y_pred = clf.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
CM = confusion_matrix(y_test, y_pred)


In [ ]:
CM

array([[81,  0,  1,  0,  0,  0,  3,  0,  3,  0],
       [ 0, 77,  0,  0,  0,  0,  1,  1,  0,  0],
       [ 0,  3, 94,  2,  1,  0,  1,  3,  2,  0],
       [ 0,  4,  1, 68,  0,  2,  0,  2,  1,  1],
       [ 1,  0,  1,  0, 99,  0,  5,  1,  1,  3],
       [ 2,  0,  0,  9,  1, 76,  3,  0,  2,  3],
       [ 2,  0,  0,  0,  2,  1, 76,  0,  1,  0],
       [ 1,  3,  1,  1,  4,  0,  0, 84,  0,  1],
       [ 1,  4,  1,  6,  1,  4,  1,  0, 60,  2],
       [ 2,  0,  1,  0,  4,  0,  0,  9,  0, 68]])

In [ ]:
rez = 0
for i in range(10):
  rez += CM[i][i]
rez  

783

In [ ]:
import pandas as pd
df = pd.read_csv('DataForPrediction_FinalTask.csv')
df_loc = df[df.id == 88].iloc[:,1:]
clf.predict_proba(df_loc).max()

0.5599692720840238

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=33, svd_solver='full').fit(X_train, y_train)


In [ ]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(criterion='gini', min_samples_leaf=10, max_depth=20, random_state=23)

clf = OneVsRestClassifier(tree).fit(pca.transform(X_train), y_train)

y_pred = clf.predict(pca.transform(X_test))

In [ ]:
CM = confusion_matrix(y_test, y_pred)
CM


array([[77,  0,  0,  1,  1,  4,  1,  0,  1,  3],
       [ 0, 74,  2,  0,  0,  0,  0,  0,  2,  1],
       [ 1,  2, 71,  5,  4,  4,  4,  2,  3, 10],
       [ 1,  1,  6, 47,  0,  8,  0,  1,  2, 13],
       [ 1,  1,  4,  1, 77,  5,  5,  2,  3, 12],
       [ 1,  1,  4, 14,  4, 46,  4,  1,  9, 12],
       [ 0,  1,  1,  1,  0,  2, 67,  0,  1,  9],
       [ 2,  3,  1,  1,  2,  2,  0, 76,  1,  7],
       [ 0,  4,  8,  4,  0,  5,  1,  0, 47, 11],
       [ 2,  0,  2,  1,  8,  3,  2,  8,  3, 55]])

In [ ]:
rez = 0
for i in range(10):
  rez += CM[i][i]
rez  

637

In [ ]:
clf.predict_proba(pca.transform(df_loc))

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])